AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false